use super::types::VerificationSpec;

#[derive(Debug, Clone)]
pub struct ContractTest {
    pub name: String,
    pub endpoint: String,
    pub method: String,
    pub assertions: Vec<ContractAssertion>,
}

/// A single assertion within a contract test.
#[derive(Debug, Clone)]
pub struct ContractAssertion {
    pub field_path: String,
    pub assertion_type: AssertionType,
    pub description: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AssertionType {
    /// Field must exist in the response.
    FieldExists,
    /// Field must have the expected type.
    FieldType { expected: String },
    /// Field must NOT exist (was removed).
    FieldAbsent,
    /// Request parameter must be included.
    ParamRequired { name: String },
    /// Request parameter type must match.
    ParamType { name: String, expected: String },
}

/// A complete contract test suite generated from verification specs.
#[derive(Debug, Clone)]
pub struct ContractTestSuite {
    pub api_name: String,
    pub old_version: String,
    pub new_version: String,
    pub tests: Vec<ContractTest>,
}

impl ContractTestSuite {
    pub fn test_count(&self) -> usize {
        self.tests.len()
    }

    pub fn assertion_count(&self) -> usize {
        self.tests.iter().map(|t| t.assertions.len()).sum()
    }

    /// Render the test suite as executable TypeScript test code.
    pub fn render_typescript(&self) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "// Auto-generated contract tests for {} ({} → {})\n",
            self.api_name, self.old_version, self.new_version
        ));
        out.push_str("// Generated by Truhowl AutoPatch\n");
        out.push_str("import { describe, it, expect } from 'vitest';\n\n");

        for test in &self.tests {
            out.push_str(&format!(
                "describe('{} {} contract', () => {{\n",
                test.method.to_uppercase(),
                test.endpoint
            ));
            for assertion in &test.assertions {
                let body = match &assertion.assertion_type {
                    AssertionType::FieldExists => {
                        format!(
                            "    expect(response).toHaveProperty('{}');",
                            assertion.field_path
                        )
                    }
                    AssertionType::FieldType { expected } => {
                        format!(
                            "    expect(typeof response.{}).toBe('{}');",
                            assertion.field_path.replace('.', "?."),
                            expected
                        )
                    }
                    AssertionType::FieldAbsent => {
                        format!(
                            "    expect(response).not.toHaveProperty('{}');",
                            assertion.field_path
                        )
                    }
                    AssertionType::ParamRequired { name } => {
                        format!("    expect(requestParams).toHaveProperty('{}');", name)
                    }
                    AssertionType::ParamType { name, expected } => {
                        format!(
                            "    expect(typeof requestParams.{}).toBe('{}');",
                            name, expected
                        )
                    }
                };
                out.push_str(&format!(
                    "  it('{}', () => {{\n{}\n  }});\n",
                    assertion.description, body
                ));
            }
            out.push_str("});\n\n");
        }
        out
    }

    /// Render the test suite as executable Python test code.
    pub fn render_python(&self) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "# Auto-generated contract tests for {} ({} -> {})\n",
            self.api_name, self.old_version, self.new_version
        ));
        out.push_str("# Generated by Truhowl AutoPatch\n");
        out.push_str("import pytest\n\n");

        for test in &self.tests {
            let class_name = sanitize_class_name(&format!(
                "Test{}{}",
                capitalize(&test.method),
                test.endpoint.replace('/', "_").replace(['{', '}'], "")
            ));
            out.push_str(&format!("class {}:\n", class_name));
            out.push_str(&format!(
                "    \"\"\"Contract tests for {} {}\"\"\"\n\n",
                test.method.to_uppercase(),
                test.endpoint
            ));

            for (i, assertion) in test.assertions.iter().enumerate() {
                let fn_name = format!("test_{}", sanitize_fn_name(&assertion.description));
                let body = match &assertion.assertion_type {
                    AssertionType::FieldExists => {
                        format!("        assert '{}' in response", assertion.field_path)
                    }
                    AssertionType::FieldType { expected } => {
                        format!(
                            "        assert isinstance(response.get('{}'), {})",
                            assertion.field_path,
                            python_type(expected)
                        )
                    }
                    AssertionType::FieldAbsent => {
                        format!("        assert '{}' not in response", assertion.field_path)
                    }
                    AssertionType::ParamRequired { name } => {
                        format!("        assert '{}' in request_params", name)
                    }
                    AssertionType::ParamType { name, expected } => {
                        format!(
                            "        assert isinstance(request_params.get('{}'), {})",
                            name,
                            python_type(expected)
                        )
                    }
                };
                out.push_str(&format!(
                    "    def {}(self, response, request_params):\n        \"\"\"{}\"\"\"  # noqa: E501\n{}\n\n",
                    if fn_name.is_empty() { format!("test_assertion_{i}") } else { fn_name },
                    assertion.description,
                    body,
                ));
            }
        }
        out
    }
}

/// Synthesize a contract test suite from a set of verification specs.
pub fn synthesize_contract_tests(
    api_name: &str,
    old_version: &str,
    new_version: &str,
    specs: &[VerificationSpec],
) -> ContractTestSuite {
    let mut tests = Vec::new();

    for spec in specs {
        let mut assertions = Vec::new();

        for field_path in &spec.fields_to_verify {
            // Determine what kind of assertion based on the field path prefix.
            if field_path.starts_with("parameters.") {
                let param_name = field_path
                    .strip_prefix("parameters.")
                    .unwrap_or(field_path)
                    .to_string();
                assertions.push(ContractAssertion {
                    field_path: field_path.clone(),
                    assertion_type: AssertionType::ParamRequired {
                        name: param_name.clone(),
                    },
                    description: format!("parameter '{}' must be present in request", param_name),
                });
            } else if field_path.starts_with("response.") {
                let resp_field = field_path
                    .strip_prefix("response.")
                    .unwrap_or(field_path)
                    .to_string();
                assertions.push(ContractAssertion {
                    field_path: resp_field.clone(),
                    assertion_type: AssertionType::FieldExists,
                    description: format!(
                        "response field '{}' must exist in new schema",
                        resp_field
                    ),
                });
            } else {
                assertions.push(ContractAssertion {
                    field_path: field_path.clone(),
                    assertion_type: AssertionType::FieldExists,
                    description: format!("field '{}' must be verified", field_path),
                });
            }
        }

        let test_name = format!(
            "{}_{}_contract",
            spec.method,
            spec.endpoint.replace('/', "_").trim_start_matches('_')
        );

        tests.push(ContractTest {
            name: test_name,
            endpoint: spec.endpoint.clone(),
            method: spec.method.clone(),
            assertions,
        });
    }

    ContractTestSuite {
        api_name: api_name.to_string(),
        old_version: old_version.to_string(),
        new_version: new_version.to_string(),
        tests,
    }
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().to_string() + c.as_str(),
    }
}

fn sanitize_class_name(s: &str) -> String {
    s.chars()
        .filter(|c| c.is_alphanumeric() || *c == '_')
        .collect()
}

fn sanitize_fn_name(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .to_lowercase()
}

fn python_type(json_type: &str) -> &str {
    match json_type {
        "string" => "str",
        "integer" => "int",
        "number" => "(int, float)",
        "boolean" => "bool",
        "array" => "list",
        "object" => "dict",
        _ => "object",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_specs() -> Vec<VerificationSpec> {
        vec![VerificationSpec {
            endpoint: "/v1/charges".into(),
            method: "post".into(),
            fields_to_verify: vec![
                "parameters.amount".into(),
                "parameters.idempotency_key".into(),
                "response.amount".into(),
                "response.fee".into(),
            ],
        }]
    }

    #[test]
    fn contracts_synthesize_produces_tests() {
        let suite =
            synthesize_contract_tests("Payments", "2024-06-01", "2026-02-15", &sample_specs());
        assert_eq!(suite.test_count(), 1);
        assert_eq!(suite.assertion_count(), 4);
    }

    #[test]
    fn contracts_synthesize_classifies_param_assertions() {
        let suite =
            synthesize_contract_tests("Payments", "2024-06-01", "2026-02-15", &sample_specs());
        let test = &suite.tests[0];
        let param_assertions: Vec<_> = test
            .assertions
            .iter()
            .filter(|a| matches!(a.assertion_type, AssertionType::ParamRequired { .. }))
            .collect();
        assert_eq!(param_assertions.len(), 2);
    }

    #[test]
    fn contracts_synthesize_classifies_response_assertions() {
        let suite =
            synthesize_contract_tests("Payments", "2024-06-01", "2026-02-15", &sample_specs());
        let test = &suite.tests[0];
        let field_assertions: Vec<_> = test
            .assertions
            .iter()
            .filter(|a| matches!(a.assertion_type, AssertionType::FieldExists))
            .collect();
        assert_eq!(field_assertions.len(), 2);
    }

    #[test]
    fn contracts_render_typescript_contains_describe() {
        let suite =
            synthesize_contract_tests("Payments", "2024-06-01", "2026-02-15", &sample_specs());
        let ts = suite.render_typescript();
        assert!(ts.contains("describe('POST /v1/charges contract'"));
        assert!(ts.contains("toHaveProperty"));
        assert!(ts.contains("import { describe, it, expect }"));
    }

    #[test]
    fn contracts_render_python_contains_class() {
        let suite =
            synthesize_contract_tests("Payments", "2024-06-01", "2026-02-15", &sample_specs());
        let py = suite.render_python();
        assert!(py.contains("class Test"));
        assert!(py.contains("def test_"));
        assert!(py.contains("import pytest"));
    }

    #[test]
    fn contracts_empty_specs_produces_empty_suite() {
        let suite = synthesize_contract_tests("API", "1", "2", &[]);
        assert_eq!(suite.test_count(), 0);
        assert_eq!(suite.assertion_count(), 0);
    }

    #[test]
    fn contracts_render_typescript_empty_is_valid() {
        let suite = synthesize_contract_tests("API", "1", "2", &[]);
        let ts = suite.render_typescript();
        assert!(ts.contains("Auto-generated"));
        assert!(!ts.contains("describe("));
    }

    #[test]
    fn contracts_render_python_empty_is_valid() {
        let suite = synthesize_contract_tests("API", "1", "2", &[]);
        let py = suite.render_python();
        assert!(py.contains("Auto-generated"));
        assert!(!py.contains("class "));
    }
}
